"""Add name column to Plant model

Revision ID: 98f01b0e8d94
Revises: 00508c8f4d08
Create Date: 2023-09-29 15:43:15.571030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f01b0e8d94'
down_revision = '00508c8f4d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('image', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('is_in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'is_in_stock')
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
